// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBENYZ83lyqeb-1FZU6Hs26qcJShQPShf0',
    appId: '1:715128702903:web:a6d95411cc96a35cba8a32',
    messagingSenderId: '715128702903',
    projectId: 'npk-sensor-51b5c',
    authDomain: 'npk-sensor-51b5c.firebaseapp.com',
    storageBucket: 'npk-sensor-51b5c.firebasestorage.app',
    measurementId: 'G-GR9Y3HXE3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9gROLTi2q2N303VPeceMZI0gcovBRwEs',
    appId: '1:715128702903:android:3657db82040452e8ba8a32',
    messagingSenderId: '715128702903',
    projectId: 'npk-sensor-51b5c',
    storageBucket: 'npk-sensor-51b5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBczzZe6Hpmncy0_9UplcOGKwS89Cg7VRc',
    appId: '1:715128702903:ios:f4f2d1fe3f2d2116ba8a32',
    messagingSenderId: '715128702903',
    projectId: 'npk-sensor-51b5c',
    storageBucket: 'npk-sensor-51b5c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBczzZe6Hpmncy0_9UplcOGKwS89Cg7VRc',
    appId: '1:715128702903:ios:f4f2d1fe3f2d2116ba8a32',
    messagingSenderId: '715128702903',
    projectId: 'npk-sensor-51b5c',
    storageBucket: 'npk-sensor-51b5c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBENYZ83lyqeb-1FZU6Hs26qcJShQPShf0',
    appId: '1:715128702903:web:7d540688e1e5051dba8a32',
    messagingSenderId: '715128702903',
    projectId: 'npk-sensor-51b5c',
    authDomain: 'npk-sensor-51b5c.firebaseapp.com',
    storageBucket: 'npk-sensor-51b5c.firebasestorage.app',
    measurementId: 'G-6QTVFBZC7G',
  );

}